# Generated by Django 4.1.4 on 2023-04-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-', verbose_name='Slug field'),
            preserve_default=False,
        ),
    ]
