# Generated by Django 4.1.4 on 2023-04-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_orderitem_product_alter_orderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descriptions',
            new_name='description',
        ),
    ]
