# Generated by Django 4.1.4 on 2023-04-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
