# Generated by Django 4.1.4 on 2023-04-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_customer_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
